### ISSUE TITLE
snake.py requires sudo

### ISSUE THREAD

**Issue by WayneKeenan** [pimoroni/unicorn-hat-hd#1]
On a Pi 3 with Wifi.

```bash
python snake.py 
xcb_connection_has_error() returned true
xcb_connection_has_error() returned true
Traceback (most recent call last):
  File "snake.py", line 141, in <module>
    screen = pygame.display.set_mode((160,160))
pygame.error: Unable to open a console terminal
```

vs 

```bash
sudo python snake.py 
xcb_connection_has_error() returned true
xcb_connection_has_error() returned true
```
There be: snakes on an (Euclidean) plane

All the other examples work without sudo.

**Comment by Gadgetoid** [comment]
That's curious. We couldn't replicate this here. What weird and wonderful configuration are you running? I'm guessing your terminal and display session are under different user contexts or something?

**Comment by Gadgetoid** [comment]
I've updated `snake.py` to use ncurses keyboard input, so it's usable via a remote SSH session. Much better! I'm going to wager that it fixes this problem.

**Comment by WayneKeenan** [comment]
Sorry, didn't see the GitHub update till now.  It was via SSH, on a Pi3 that has been thru many demos. It was also one of your beta boards, but I can't see that having any effect. Will test and let you know.
