### ISSUE TITLE
Some example broken with Raspbian Stretch Lite

### ISSUE THREAD

**Issue by dglaude** [pimoroni/unicorn-hat-hd#10]
On a fresh new install, using "pimoroni-dashboard" and fully update minutes ago, some examples are not working. Not sure I got exactly the same version of the example as on github, but I'll assume so as this place has not been updated recently.

Most notably and strange one is "stars.py" and I know this was working with last version of Raspbian:

> ~/Pimoroni/unicornhathd/examples $ python3 stars.py 
> Unicorn HAT HD: Stars
> 
> This example simulates a wooshing star field.
> 
> Press Ctrl+C to exit!
> 
> 
> Traceback (most recent call last):
>   File "stars.py", line 41, in <module>
>     unicornhathd.set_pixel(stars[i][0], stars[i][1], v, v, v)
>   File "/usr/lib/python3/dist-packages/unicornhathd/__init__.py", line 79, in set_pixel
>     _buf[x][y] = r, g, b
> IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Other example just need a little help (I did not test if it is due to "lite" or "stretch"):

"text.py" and "rainbow-text.py" were failing on me, but this solved the problem:
> sudo apt install fonts-roboto
(it could be printed at first run or when the exception is raised)

"snake.py" does not work as it need pygame but this solve it for me:
> sudo apt-get install python-pygame
(it could be detected as missing at the import time and display instruction to fix it)

PS: I did not test raspicam.py as I had not cam at hand.

**Comment by Gadgetoid** [comment]
I think the issue with stars is this one here, which has since been resolved: https://github.com/pimoroni/unicorn-hat-hd/issues/15

It's clear the OLI needs updating to include these additional dependencies (optionally) too.
