### ISSUE TITLE
UniHatHD Lights

### ISSUE THREAD

**Issue by flash76** [pimoroni/unicorn-hat-hd#12]
Hi guys... I just received my Unicorn HD Today and right off the bat I'm having some problems. I was on Raspbian Stretch but then I downgraded to Jessie thinking that maybe it was incompatible. But still my matrix isn't lighting up AT ALL when I run a demo. I don't think the board is fried because occasionally a row lights up dimly or brightly when I seat the HAT on the GPIO. Why is this happening? I've run the one-time installer.

**Comment by Gadgetoid** [comment]
Which installer did you run/what examples are you running?

**Comment by flash76** [comment]
I used the one line installer and I'm running paint, stars, candle, test, text, game of life, forest-fire

**Comment by Gadgetoid** [comment]
Okay so definitely not the old Unicorn HAT library then! (It happens)

Was the downgrade to Jessie a fresh install? (Honestly I don't think there's any other way, but process of elimination and whatnot)

**Comment by flash76** [comment]
Yep. I scavenged downloads.raspberrypi.org for the last release of Raspbian Jessie and wrote it to the SD card with Etcher (though I didn't format it, which may be the problem). But anyway, yes. It was a clean install.

**Comment by Gadgetoid** [comment]
It sounds very much like a dud Unicorn HAT HD- there have been a couple. You should drop us a message at support@pimoroni.com with your order details to arrange a replacement. Sorry about that :(

**Comment by flash76** [comment]
I ordered my Unicorn HAT HD off of Amazon...Would I use that order number on the included receipt?

**Comment by Gadgetoid** [comment]
Yes, I believe so, although it's only relevant if you ordered from us via Amazon.

**Comment by flash76** [comment]
Does this also happen from a static shock? I really would like to believe that this matrix is still working...going back to one row lighting up when plugged in, it is column 2 closest to the "UNICORN HAT HD" text.

**Comment by flash76** [comment]
I've finally recieved my replacement and NOTHING WORKS. After a fresh install of Raspbian Stretch, I still can't get this to work.

**Comment by flash76** [comment]
Sorry about this, it was all a mix-up on my part. I didn't connect the board securely into place, because I was being too "careful" with everything. I'm really sorry about this.
