### ISSUE TITLE
Request for more consistent examples

### ISSUE THREAD

**Issue by lurch** [pimoroni/unicorn-hat-hd#26]
Only a few small niggles, but it would be nice if these could be tidied up. I recently bought a Unicorn Hat HD from https://www.raspberrypi.org/blog/guess-what/ and finally got round to playing with it this evening. I quickly ran through the example demos and noticed:
 1. Not all demos use the same "up direction", meaning you have to keep spinning round your Pi to get each of the demos "looking correct"
 2. Not all demos display the helpful "Press Ctrl+C to exit"
 3. Seems like some demos clear the Unicorn HAT when they exit, but others just leave whatever was last being displayed as still visible

Haven't tried writing any of my own code yet, but the hardware and the demos seem really good :grinning:

**Comment by lurch** [comment]
P.S. Is `rainbow-2x1.py` _supposed_ to be in this repo? It's not obvious from the filename that it's for the Ubercorn and not the Unicorn HAT HD.

**Comment by sandyjmacdonald** [comment]
Yes, it's appears that `camera.py` and `raspicam.py` were pretty much the same as each other! I've removed the latter in my PR. I've also renamed that example to make it a bit clearer what it is. Thanks for prompting us to do this. :-)

**Comment by Gadgetoid** [comment]
I wholly approve this kind of feedback! I'm keenly aware that our software ecosystem is basially a crumbtrail of our growth over the last 5-6 years, and much of it is patchy and inconsistent and many repositories get neglected as my attention turns to newer projects and products.

It's my long-standing goal to audit older repositories and make everything neat and tidy across the board, but it's often hard to see the woods for the trees.

Thank you both!
