### ISSUE TITLE
Missing Font in Raspbian Lite

### ISSUE THREAD

**Issue by matthew1471** [pimoroni/unicorn-hat-hd#30]
Hi :smile:

Was scratching my head trying to work out why text demos don't work. Looked at the source and spotted I'm missing a font in the expected path.

Fix was:
`apt-get install fonts-freefont-ttf`

Suggest adding fonts-freefont-ttf as a dep to https://get.pimoroni.com/unicornhathd

Kind Regards,
Matthew

**Comment by Gadgetoid** [comment]
Good spot! Thank you. This should now be included in the installer.
