### ISSUE TITLE
example heartbeats.py fail on python3

### ISSUE THREAD

**Issue by dglaude** [pimoroni/unicorn-hat-hd#32]
The title says it all.
Python 2 only code should be banish...

`
Traceback (most recent call last):
  File "heartbeats.py", line 46, in <module>
    for i in 2 * (range(10, 0, -1) + range(1, 10)):
TypeError: unsupported operand type(s) for +: 'range' and 'range'
`

**Comment by Robtom5** [comment]
Could swap this to being a list comprehension instead?

for i in [2*elem for ranges in (range(10, 0, -1), range(1, 10)) for elem in ranges):

(tested on my pi and seems to work)

**Comment by Robtom5** [comment]
Example I gave wasn't quite right, but correct version for a pulse is in my PR. I don't believe I have the ability to update the learn article

**Comment by Gadgetoid** [comment]
Drat I suggested the `range() + range()` approach to simplify the code, completely forgetting that Python 3 returns a lazy range rather than a list.

The code and tutorial already differ- and I don't think that matters too much, but the not-working-in-Python-3 is a bit of a gotcha.

**Comment by Gadgetoid** [comment]
Fixed! Thank you for pointing it out. I really need to add example testing to the CI!
