### ISSUE TITLE
Orientation should be uniform across all examples

### ISSUE THREAD

**Issue by Robtom5** [pimoroni/unicorn-hat-hd#35]
Building from #26. Examples currently follow no clear orientation rule, following from work in heartbeats.py I propose that all examples be orientated such that they have the same orientation as the text on the back of the pcb, even those that are technically are direction independant (such as game of life). 

This will involve setting the rotation to 270 degrees at the start of all examples.

In the same vein the brightness should probably also be set to a standard level / a standard example template constructed that can be called in each example.

**Comment by Gadgetoid** [comment]
Good points. I don't disagree. However, time is my enemy!
