### ISSUE TITLE
Rename brightness(), to set_brightness()

### ISSUE THREAD

**Issue by neauoire** [pimoroni/unicorn-hat-hd#37]
I like the `set_brightness` from the blinkt class, I was wondering why this is just `.brightness()`

**Comment by Gadgetoid** [comment]
We'd have to have both a `brightness` and a `set_brightness` to avoid breaking changes to old code, but I don't disagree. `set_` is clearer about intent.

**Comment by iamsrp** [comment]
FYI, the version installed via pip3 looks like it is now out of date, it only has the `brightness()` function.

**Comment by Gadgetoid** [comment]
You're right- this is very overdue a release... just a few changes since 0.0.4 - https://github.com/pimoroni/unicorn-hat-hd/compare/v0.0.4...master
