### ISSUE TITLE
bug: show_my_ip displays the ip address regardless of the argument to scroll_text()

### ISSUE THREAD

**Issue by zencuke** [pimoroni/unicorn-hat-hd#39]
This bug is only seen if the user tries to use scroll_text() to show something other than the ip address.
 
The fix is simple: In the function **def create_image_from_text(in_text):** the call:
```
    draw.text((text_x, text_y), my_ip, colours, font=font)
```
should be:
```
    draw.text((text_x, text_y), in_text, colours, font=font)
```
The demo works only when the values of the in_text and my_ip variables are the same. The user will only see the bug if they modify the code to use the **scroll_text()** function to  show something else besides the ip address.

The root problem is that as written the variable my_ip has global scope. If the main code was in a function instead  the variable my_ip would have been local to that function and create_image_from_text() would have failed because my_ip would no longer be global and therefor not in scope to the code in that function.

The following design pattern is more robust and would have revealed the error before the code was released:

```
def do_main_stuff():
    <main code>

if __name__ == '__main__':
    do_main_stuff()

```

**Comment by Gadgetoid** [comment]
Good spot, added a quick-fix and hopefully haven't broken anything!
