### ISSUE TITLE
Detecting hat using EEPROM Product ID.

### ISSUE THREAD

**Issue by SeanCline** [pimoroni/unicorn-hat-hd#47]
Hello!

I'd like to detect whether the Unicorn HAT HD is installed so my [Gif2UnicornHat](https://github.com/SeanCline/Gif2UnicornHat) tool can automatically work on both the Unicorn HAT and the Unicorn HAT HD.

With the Unicorn HAT, I can just `cat /proc/device-tree/hat/product` and it tells me I have a `Unicorn HAT` installed. That's not so with the Unicorn HAT HD. I get `No such file or directory.`

I see that the Unicorn pHAT [has no EEPROM](https://forums.pimoroni.com/t/pi-thinks-unicorn-hat-is-a-phat/2682/8) which means no auto-detect even though [the pinout](https://pinout.xyz/pinout/unicorn_phat) says it has an `EEPROM product ID`.

So, is there some way to detect this? Or perhaps pinout.xyz is wrong for both the [Unicorn pHAT](https://pinout.xyz/pinout/unicorn_phat) and [Unicorn HAT HD](https://pinout.xyz/pinout/unicorn_hat_hd)?

**Comment by Gadgetoid** [comment]
The pHAT does not have an EEPROM (No pHAT products do), Pinout is wrong :grimacing:
