### ISSUE TITLE
API documentation 0.0.1 is not up to date with code.

### ISSUE THREAD

**Issue by dglaude** [pimoroni/unicorn-hat-hd#8]
[http://docs.pimoroni.com/unicornhathd/#](API documentation) refer to x and y from 0 to 7 where in the code inline comment, it is obviously from 0 to 15.

Dunno how you create content on docs.pimoroni.com, but you should regenerate it.

**Comment by Gadgetoid** [comment]
Good spot thanks, I've updated the docs. This is probably something I need to automate.
