### ISSUE TITLE
No mention that SPI needs to be enabled

### ISSUE THREAD

**Issue by x60813** [pimoroni/unicorn-hat-hd#9]
Please can the need to enable SPI be added to the readme.md file. As I get the below error if SPI is not enabled.

`>>> import unicornhathd`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
 ` File "/usr/local/lib/python3.4/dist-packages/unicornhathd/__init__.py", line 20, in <module>`
`    _spi.open(0, 0)`
`FileNotFoundError: [Errno 2] No such file or directory`

This is on a Raspberry Pi Zero W, Python 3.4.2.

**Comment by Mutiny-Games** [comment]
This should be addressed in pull request #14
